# Generated by Django 5.1.3 on 2025-02-23 17:09

import core.models.document
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'ordering': ['-created_at'],
                'permissions': [('view_business_documents', 'Can view business documents'), ('upload_business_documents', 'Can upload business documents')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('agency_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='core.customer'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('agency_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('businesses', models.ManyToManyField(related_name='documents', through='core.BusinessDocument', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_make_public', 'Can make document public'), ('can_make_private', 'Can make document private')],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_id', models.CharField(help_text='Unique identifier for the field', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.document')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('document', 'Document'), ('phone', 'Phone'), ('email', 'Email')], default='manual', max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='ID reference to the source (document, phone, or email) if not manual', null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='core.business')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.field')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedBusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for the document', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document', null=True)),
                ('file', models.FileField(help_text='The uploaded document file', upload_to=core.models.document.uploaded_business_document_path)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='core.business')),
            ],
            options={
                'verbose_name': 'Uploaded Business Document',
                'verbose_name_plural': 'Uploaded Business Documents',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['agency_owner', 'created_at'], name='core_custom_agency__65954b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='core_custom_email_899d12_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='core_custom_phone_n_b7f97e_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['customer', 'created_at'], name='core_busine_custome_39faef_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='core_busine_name_b3e876_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['email'], name='core_busine_email_21974f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['agency_owner', 'is_public'], name='core_docume_agency__2b5b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['name'], name='core_docume_name_c35e16_idx'),
        ),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['business', 'status'], name='core_busine_busines_625006_idx'),
        ),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['document', 'status'], name='core_busine_documen_d01e92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessdocument',
            unique_together={('business', 'document')},
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['document', 'field_id'], name='core_field_documen_cf59a8_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['field_type'], name='core_field_field_t_4c6dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['business', 'source'], name='core_fieldv_busines_e32ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['field', 'source'], name='core_fieldv_field_i_509cae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('field', 'business')},
        ),
        migrations.AddIndex(
            model_name='uploadedbusinessdocument',
            index=models.Index(fields=['business', 'created_at'], name='core_upload_busines_6170e6_idx'),
        ),
    ]
