# Generated by Django 5.1.3 on 2025-02-23 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('agent', 'Agent'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency User',
                'verbose_name_plural': 'Agency Users',
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='users',
            field=models.ManyToManyField(related_name='agencies', through='core.AgencyUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agencyuser',
            index=models.Index(fields=['user', 'agency'], name='core_agency_user_id_df44e6_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyuser',
            index=models.Index(fields=['agency', 'role'], name='core_agency_agency__8a113e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyuser',
            unique_together={('user', 'agency')},
        ),
    ]
